//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/InputActions/PlayerActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerActions"",
    ""maps"": [
        {
            ""name"": ""Entradas"",
            ""id"": ""76a75636-424c-4d1f-b2a6-29748f07ac71"",
            ""actions"": [
                {
                    ""name"": ""SpacePressed"",
                    ""type"": ""Button"",
                    ""id"": ""08c18125-dc6e-4e43-9393-85e19a0bc612"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""dcfb086f-6d0c-465c-807c-fdb7809743a0"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpacePressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Entradas
        m_Entradas = asset.FindActionMap("Entradas", throwIfNotFound: true);
        m_Entradas_SpacePressed = m_Entradas.FindAction("SpacePressed", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Entradas
    private readonly InputActionMap m_Entradas;
    private IEntradasActions m_EntradasActionsCallbackInterface;
    private readonly InputAction m_Entradas_SpacePressed;
    public struct EntradasActions
    {
        private @PlayerActions m_Wrapper;
        public EntradasActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @SpacePressed => m_Wrapper.m_Entradas_SpacePressed;
        public InputActionMap Get() { return m_Wrapper.m_Entradas; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(EntradasActions set) { return set.Get(); }
        public void SetCallbacks(IEntradasActions instance)
        {
            if (m_Wrapper.m_EntradasActionsCallbackInterface != null)
            {
                @SpacePressed.started -= m_Wrapper.m_EntradasActionsCallbackInterface.OnSpacePressed;
                @SpacePressed.performed -= m_Wrapper.m_EntradasActionsCallbackInterface.OnSpacePressed;
                @SpacePressed.canceled -= m_Wrapper.m_EntradasActionsCallbackInterface.OnSpacePressed;
            }
            m_Wrapper.m_EntradasActionsCallbackInterface = instance;
            if (instance != null)
            {
                @SpacePressed.started += instance.OnSpacePressed;
                @SpacePressed.performed += instance.OnSpacePressed;
                @SpacePressed.canceled += instance.OnSpacePressed;
            }
        }
    }
    public EntradasActions @Entradas => new EntradasActions(this);
    public interface IEntradasActions
    {
        void OnSpacePressed(InputAction.CallbackContext context);
    }
}
